[tools]
aws-sam = "latest"
azure-cli = "latest"
lazydocker = "latest"
lazygit = "latest"
terraform = "latest"

lua-language-server = "latest"

#editors
neovim = "latest"
vim = "latest"

# node
node = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:prettier" = "latest"

# python
pipx = "latest"
"pipx:black" = "latest"
"pipx:pylint" = "latest"
python = "latest"

# rust
rust = "latest"

# formatter
fzf = "latest"
jq = "latest"
# linter
cfn-lint = "latest"
yamllint = "latest"
shellcheck = "latest"
"npm:jsonls" = "latest"
