[tools]
aws-sam = "latest"
azure-cli = "latest"
lazydocker = "latest"
lazygit = "latest"
terraform = "latest"

#editors
vim = "latest"

# node&npm
node = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:prettier" = "latest"
"npm:jsonls" = "latest"
"npm:ts-node" = "latest"
"npm:typescript" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@typescript-eslint/eslint-plugin" = "latest"
"npm:@typescript-eslint/parser" = "latest"

# python
python = "latest"
pipx = "latest"
"pipx:black" = "latest"
"pipx:pylint" = "latest"


# rust
rust = "latest"

# formatter
fzf = "latest"
jq = "latest"

# linter
cfn-lint = "latest"
yamllint = "latest"
shellcheck = "latest"

# other
1password = "latest"

